package com.github.oeuvres.alix.web;

public class Pars
{
    private Pars() {}
    public static final String ALIX_META        = "alix.meta";
    public static final String ALIX_PARS        = "alix.pars";
    public static final String BM25             = "bm25";
    public static final String CTX              = "ctx";
    public static final int    CTX_DEFAULT      = 10;
    public static final String CTX_LEFT         = "ctxleft";
    public static final int[]  CTX_RANGE        = {0, 200};
    public static final String CTX_RIGHT        = "ctxright";
    public static final String DATE             = "date";
    public static final String DOCLINE          = "docline";
    public static final String DOCNAME          = "docname";
    public static final String DOCID            = "docid";
    public static final String DOCS             = "docs";
    public static final int    DOCS_DEFAULT     = 100;
    public static final int[]  DOCS_RANGE       = {1, 500};
    public static final String END              = "end";
    public static final String FTEXT            = "ftext";
    public static final String FYEAR            = "fyear";
    public static final String FROM             = "from";
    public static final String INFIX            = "infix";
    public static final String IDFEXP           = "idfexp";
    public static final Double IDFEXP_DEFAULT   = 1.0;
    public static final String LEFT             = "left";
    public static final int    LEFT_DEFAULT     = 5;
    public static final int[]  LEFT_RANGE       = {0, 200};
    public static final String LOG_LIKELIHOOD   = "loglikelihood";
    public static final String LOG_RATIO        = "logratio";
    public static final String Q                = "q";
    public static final String RIGHT             = "right";
    public static final int    RIGHT_DEFAULT     = 5;
    public static final int[]  RIGHT_RANGE       = {0, 200};
    public static final String ROWS             = "rows";
    public static final int    ROWS_DEFAULT     = 2000;
    public static final int[]  ROWS_RANGE       = {1, 2000};
    public static final String SCORER           = "scorer";
    public static final String SIMPLE_MATHS     = "simplemaths";
    public static final String SLOP             = "slop";
    public static final int    SLOP_DEFAULT     = 20;
    public static final int[]  SLOP_RANGE       = {0, 200};
    public static final String SMOOTH           = "smooth";
    public static final String SNIPPETS         = "snippets";
    public static final int    SNIPPETS_DEFAULT = 3;
    public static final int[]  SNIPPETS_RANGE   = {-1, 100};
    public static final String SORT             = "sort";
    public static final String START            = "start";
    public static final String TERMS            = "terms";
    public static final int    TERMS_DEFAULT    = 50;
    public static final int[]  TERMS_RANGE      = {1, 5000};
    public static final String TFLAG            = "tflag";
    public static final String TSORT            = "tsort";
    public static final String TYPE             = "type";
    public static final String XTICKS           = "xticks";
    public static final int[]  XTICKS_DEFAULT   = {5, 10, 20, 50, 100, 200, 500};
    public static final int[]  XTICKS_RANGE     = {0, 1000};
    public static final String YEAR             = "year";
}
