package site.oeuvres.util;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.StringWriter;
import java.io.Writer;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * A specialized table for a dictionary of terms with count and int key (starting at 1).
 * Access by String (internal HashMap), by an int key (internal array, for optimized vector).
 * Useful methods to get term list in inverse frequency order.
 * 
 * Each term added will create an entry or increment a counter if already
 * exists. Int id, generated by an internal autoincrement pointer.
 * It’s a grow only object, entries can’t be removed.
 * There’s no method to put a term with a free key, terms are never replaced and
 * keep their index. Ids are kept consistent during all life of Object, but may
 * be lost on saving (TODO) and dictionary merges (TODO).
 * 
 * TODO implement saving on SQL backend
 * 
 * @author glorieux-f
 *
 */
public class TermDic
{
  /** Position of the term index in the array of int values */
  private static final int CODE = 0;
  /** Position of the term counter in the array of int values */
  private static final int COUNT1 = 1;
  /** Position of the second counter in the array of int values */
  private static final int COUNT2 = 2;
  /** Pointer in the array, only growing when terms are added, used as code */
  private int code;
  /** HashMap to find String fast, int array contains an int key and a count  */
  private HashMap<String,int[]> byTerm;
  /** List of terms, kept in index order, to get a term by int index */
  private String[] byIndex;
  /** Count of all occurrences for this dico */
  private int occs;
  /** Last occurrences count before some ops, for caching */
  // private int lastOccs;

  /**
   * Constructor
   */
  public TermDic()
  {
    byTerm = new HashMap<String, int[]>();
    byIndex = new String[32];
  }

  
  /**
   * Get a term by index
   * Be Careful, returned term is mutable, modification will affect the dictionary.
   * Power is delicate.
   * 
   * @param index
   * @return the term
   */
  private String term( final int index )
  {
    if (index < 1)
      return null;
    if (index > code)
      return null;
    return byIndex[index];
  }
  /**
   * Get a term by index 
   * @param index
   * @return The term as a string
   */
  public String string( final int index )
  {
    return term(index).toString();
  }

  /**
   * Get the index of a term, 0 if not found
   * 
   * @param term
   * @return the key
   */
  public int index( Term term )
  {
    int[] value = byTerm.get( term );
    if (value == null)
      return 0;
    return value[CODE];
  }

  /**
   * Get the count of a term, 0 if not found
   * 
   * @param term
   * @return the count of occurrences
   */
  public int count( Term term )
  {
    int[] value = byTerm.get( term );
    if (value == null)
      return 0;
    return value[COUNT1];
  }

  /**
   * Get the count of a term by index, 0 if not found
   * 
   * @param index
   *          a term index
   * @return the state of counter after increments
   */
  public int count( int index )
  {
    int[] value = byTerm.get( byIndex[index] );
    if (value == null)
      return 0;
    return value[COUNT1];
  }

  /**
   * Increment a term, create it if not exists
   * 
   * @param term
   * @return the index created
   */
  public int add( final String term )
  {
    return add( term, 1, 0 );
  }
  public int add( final Term term )
  {
    return add( term, 1, 0 );
  }
  public int add2( final String term )
  {
    return add( term, 0, 1);
  }
  public int add2( final Term term )
  {
    return add( term, 0, 1);
  }
  public int add ( final String term, final int count)
  {
    return add( term, count, 0 );
  }
  public int add ( final Term term, final int count)
  {
    return add( term, count, 0 );
  }
  /**
   * Add a list of terms
   * 
   * @param term
   * @return better idea than void ?
   */
  /*
  public void add( String[] bag )
  {
    int length = bag.length;
    for ( int i=0; i<length; i++)
      add( bag[i], 1 );
  }
  */

  /**
   * Add a term occurrence, increment if exist or create entry
   * @param term
   * @param count1 first count
   * @param count2 second counter
   * @return
   */
  public int add( final String term, final int count1, final int count2 )
  {
    // this code is repeated to not copy the transmitted term 
    int[] value = byTerm.get( term );
    occs += count1;
    occs += count2;
    if (value == null) return put( term, count1, count2);
    value[COUNT1] += count1;
    value[COUNT2] += count2;
    return value[CODE];
  }
  
  private int put ( final String term, final int count1, final int count2 )
  {
    code++;
    // index is too short, extends it (not a big perf pb)
    if (code >= byIndex.length) {
      final int oldLength = byIndex.length;
      final String[] oldData = byIndex;
      byIndex = new String[oldLength * 2];
      System.arraycopy( oldData, 0, byIndex, 0, oldLength );
    }
    byTerm.put( term, new int[] { code, count1, count2 } );
    byIndex[code] = term;
    return code;
  }
  /**
   * Add a term occurrence, increment if exist or create entry
   * @param term
   * @param count1 first count
   * @param count2 second counter
   * @return
   */
  public int add( final Term term, final int count1, final int count2 )
  {
    // this code is repeated to not copy the transmitted term 
    int[] value = byTerm.get( term );
    occs += count1;
    occs += count2;
    if (value == null) return put( term.toString(), count1, count2);
    value[COUNT1] += count1;
    value[COUNT2] += count2;
    return value[CODE];
  }
  
  /**
   * Size of the dictionary
   */
  public int size()
  {
    return code;
  }

  /**
   * Sum of all counts
   */
  public int occs()
  {
    return occs;
  }
  /**
   * Get term list in inverse count order.
   * @return 
   */
  public Term[] byCount()
  {
    return byCount( -1 );
  }
  /**
   * Used for freqlist, return a view of the map sorted by term count
   * Shall we cache ?
   * @param limit
   * @return
   */
  public Term[] byCount(int limit)
  {
    // Do not use LinkedList nere, very slow access by index list.get(i), arrayList is good
    List<Map.Entry<String, int[]>> list = new ArrayList<Map.Entry<String, int[]>>( byTerm.entrySet() );
    Collections.sort( list, new Comparator<Map.Entry<String, int[]>>()
    {
      @Override
      public int compare( Map.Entry<String, int[]> o1, Map.Entry<String, int[]> o2 )
      {
        return o2.getValue()[COUNT1] - o1.getValue()[COUNT1];
      }
    } );
    int size = Math.min( list.size(), limit ) ;
    if ( limit < 1 ) size = list.size();
    Term[] byCount = new Term[size];
    for (int i = 0; i < size; i++) {
      byCount[i] = new Term(list.get( i ).getKey()) ;
    }
    return byCount;
  }

  /**
   * To save the dictionary, with some index consistency but… will not works on
   * merge
   * 
   * @param file
   * @throws NumberFormatException
   * @throws IOException
   */
  public void csv( Path path ) throws IOException
  {
    BufferedWriter writer = Files.newBufferedWriter( path, Charset.forName( "UTF-8" ) );
    csv( writer );
  }

  /**
   * Send a CSV version of the dictionary
   * 
   * @return a CSV string
   */
  public String csv()
  {
    return csv( 0, null );
  }

  /**
   * Send a CSV version of the dictionary
   * 
   * @return a CSV string
   */
  public String csv( int limit )
  {
    return csv( limit, null );
  }

  /**
   * Send a CSV version of the dictionary
   * 
   * @return a CSV string
   */
  public String csv( int size, Set<Term> stoplist )
  {
    String ret = null;
    try {
      ret = csv( new StringWriter(), size, stoplist ).toString();
    } catch (IOException e) {
      e.printStackTrace();
    }
    return ret;
  }

  /**
   * Give a csv view of all dictionary
   * 
   * @throws IOException
   */
  public Writer csv( Writer writer ) throws IOException
  {
    return csv( writer, -1, null );
  }

  /**
   * Give a csv view of all dictionary
   * 
   * @throws IOException
   */
  public Writer csv( Writer writer, int limit, Set<Term> stoplist ) throws IOException
  {
    Term[] byCount = byCount();
    int length = byCount.length;
    int count1;
    int count2;
    try {
      for (int i = 0; i < length; i++) {
        if (stoplist != null && stoplist.contains( byCount[i] ))
          continue;
        if (limit-- == 0)
          break;
        int[] value = byTerm.get( byCount[i] );
        count1 = value[COUNT1];
        count2 = value[COUNT2];
        writer.write( 
                byCount[i]
          +"\t"+ count1
          +"\t"+ count2
          +"\t"+ (count1+count2)
          +"\t"+NumberFormat.getInstance().format( 1.0*count1 / (count1+count2) )
          // +"\t"+index(byCount[i])
        +"\n" );
      }
    } finally {
      writer.close();
    }
    return writer;
  }

  /**
   * Is used for debug, is not a save method
   */
  @Override
  public String toString()
  {
    return csv( 10 );
  }

  /**
   * Load a freqlist from csv TODO test it
   * 
   * @param file
   * @throws IOException
   * @throws NumberFormatException
   */
  public void load( Path path ) throws IOException
  {
    BufferedReader reader = Files.newBufferedReader( path, Charset.forName( "UTF-8" ) );
    String line = null;
    int value;
    try {
      // pass first line
      line = reader.readLine();
      while ((line = reader.readLine()) != null) {
        if (line.contains( "\t" )) {
          String[] strings = line.split( "\t" );
          try {
            value = Integer.parseInt( strings[1] );
          } catch (NumberFormatException e) {
            continue;
          }
          add( strings[0].trim(), value );
        }
        else {
          add( line.trim() );
        }
      }
    } finally {
      reader.close();
    }
  }

  /**
   * Testing
   * 
   * @throws IOException
   */
  public static void main( Term[] args ) throws IOException
  {
    String text = "un texte court avec un peu des mots un peu pareils des";
    // Term t = new Term();
    TermDic dic = new TermDic();
    for ( String s: text.split( " " ) ) {
      // t.replace( s ); // Mutable key is OK
      dic.add( s );
    }
    System.out.println( dic );
    
  }
}
